### ISSUE TITLE
Publish Docker images elsewhere than Docker Hub 

### ISSUE THREAD

**Issue by laurentlbm** [webrecorder/pywb#826]
It seems that [organisations will be removed from Docker Hub unless they have a paid plan](https://news.ycombinator.com/item?id=35166317). Is Webrecorder/pywb impacted? If it is, then all the Docker images will be deleted and a lot of people will be affected. 

Can you publish the images elsewhere? Popular options are GitHub's repository ([ghcr.io](https://www.ghcr.io)) and [quay.io](https://www.quay.io).

**Comment by ikreymer** [comment]
Yes, this is definitely a concern, and seems a bit unfortunate. We are looking into subscribing for the 'webrecorder/' org docker images, but also using an alternative repository seems like a good idea as well. Seems like this issue is getting a lot of attention, so we'll see where things are at in the next week. Will report any updates here.

**Comment by tw4l** [comment]
Docker has since published an update saying that existing public images will not be deleted and existing namespaces will not be made available, so references existing Dockerhub images should continue to work without a security risk regardless of what we do moving forward.

https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/

**Comment by tw4l** [comment]
Docker has now fully reversed their plan to sunset the Free Teams plan, so we will be keeping images on Docker Hub for the foreseeable future. Thanks for bringing this to our attention!
